
server:
  port: 8089
  servlet:
    context-path: /acv
kafka:
  producer:
    bootstrap-servers: localhost:9092
#management:
#  health:
#    livenessState.enabled: true
#    readinessState.enabled: true
#  endpoint.health.probes.enabled: true

#spring:
#  application.name: service-acv
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka