
server:
  port: 8093
  servlet:
    context-path: /acv

#management:
#  health:
#    livenessState.enabled: true
#    readinessState.enabled: true
#  endpoint.health.probes.enabled: true

#spring:
#  application.name: service-acv
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka